export const BEAT_LIST_REQUEST = 'BEAT_LIST_REQUEST';
export const BEAT_LIST_SUCCESS = 'BEAT_LIST_SUCCESS';
export const BEAT_LIST_FAIL = 'BEAT_LIST_FAIL';

export const BEAT_DETAILS_REQUEST = 'BEAT_DETAILS_REQUEST';
export const BEAT_DETAILS_SUCCESS = 'BEAT_DETAILS_SUCCESS';
export const BEAT_DETAILS_FAIL = 'BEAT_DETAILS_FAIL';


export const BEAT_SAVE_REQUEST = 'BEAT_SAVE_REQUEST';
export const BEAT_SAVE_SUCCESS = 'BEAT_SAVE_SUCCESS';
export const BEAT_SAVE_FAIL = 'BEAT_SAVE_FAIL';

export const BEAT_DELETE_REQUEST = 'BEAT_DELETE_REQUEST';
export const BEAT_DELETE_SUCCESS = 'BEAT_DELETE_SUCCESS';
export const BEAT_DELETE_FAIL = 'BEAT_DELETE_FAIL';
